### ISSUE TITLE
404 Page Not Found handling

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/genomics-status#142]
Currently, this is all what we see when a page is not found: 

```python
Traceback (most recent call last):
  File "/home/genomics.www/anaconda/envs/web/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1309, in _execute
    result = self.prepare()
  File "/home/genomics.www/anaconda/envs/web/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1998, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```

Handle this situation to show a nicer message...

**Comment by Galithil** [comment]
Pr was merged, we now have a nice 404 handling.
